### ISSUE TITLE
Command "npm test" filed

### ISSUE THREAD

**Issue by grazumkov** [rmurphey/js-assessment#189]
Error when running tests on the command line (npm test):

```
C:\Temp\js-assessment\node_modules\mocha\lib\utils.js:634
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) ''tests/app''
    at Object.lookupFiles (C:\Temp\js-assessment\node_modules\mocha\lib\utils.js              :634:15)
    at C:\Temp\js-assessment\node_modules\mocha\bin\_mocha:327:30
    at Array.forEach (native)
    at Object.<anonymous> (C:\Temp\js-assessment\node_modules\mocha\bin\_mocha:3              26:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm ERR! Test failed.  See above for more details.
```

**Comment by rmurphey** [comment]
This is likely due to the use of `/` as the separator for the path in the `test` command in package.json. I'm not sure what the options are for fixing this in package.json without breaking it for Unix/Mac users; in the meantime, changing occurrences of `/` to `\` may get you up and running locally.

**Comment by grazumkov** [comment]
1. What if remove single quotes?
2. We can make the mocha launch script. See [my commit](https://github.com/xtratio/js-assessment/commit/0120bff25179cb1fe8b571a3f3f69757c218c78d)
